*&---------------------------------------------------------------------*
*& Include          ZMDIK_P73_I002
*&---------------------------------------------------------------------*



SELECTION-SCREEN BEGIN OF BLOCK bl WITH FRAME TITLE text-t01.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 5(20) text-001 FOR FIELD proc_t .
  PARAMETERS proc_t TYPE ZMDKP_DE015  AS LISTBOX VISIBLE LENGTH 20 OBLIGATORY.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT 5(20) text-002 FOR FIELD s_kod.
  PARAMETERS s_kod TYPE bukrs OBLIGATORY.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK bl.
